# -*- coding: utf-8 -*-
"""Sentiment3Ashish.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fspxvEdrDZYbXGXDIUGozgXGPOb1jQLn
"""

import pandas as pd

data = pd.read_csv("Dataset-SA.csv")
data.head(5)

df = data.drop(columns=["product_name","product_price","Rate","Review"])
df.head()

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

df['Summary'] = df['Summary'].fillna('')

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

nltk.download('stopwords')
nltk.download('punkt')
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
  words = word_tokenize(text)
  filtered = [stemmer.stem(word.lower()) for word in words if word.isalnum() and word.lower() not in stop_words]
  return ' '.join(filtered)

df['Summary'] = df['Summary'].apply(preprocess)

from sklearn.model_selection import train_test_split

X = data['Summary'].fillna('')
y = data['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_tfidf)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy", accuracy)

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='weighted')
print(precision)

from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred, average='weighted')
f1

def fun(user_input):
  preprocessed_input = preprocess(user_input)
  input_tfidf = vectorizer.transform([preprocessed_input])
  predicted_sentiment = model.predict(input_tfidf)
  return predicted_sentiment

a=input("enter your review")
print("review of product is ",fun(a))# positive

b=input("enter your review")
print("review of product is ",fun(b))# negative

c=input("enter your review")
print("review of product is ",fun(c))# neutral